"use strict";
const C={H:'#fff',C:'#444',N:'#3050f8',O:'#ff0d0d',Na:'#ab5cf2',Cl:'#1ff01f',Si:'#f0c8a0',S:'#ffff30'},R={H:.35,C:.55,N:.55,O:.55,Na:.7,Cl:.6,Si:.6,S:.6};
const q=s=>document.querySelector(s),can=q('#canvas'),ctx=can.getContext('2d'),ui={file:q('#file'),cut:q('#cutoff'),name:q('#name'),status:q('#status'),empty:q('#empty'),total:q('#total'),stats:q('#stats'),radii:q('#radii')};let S,hover,drag,cam={x:25,y:-35,z:60,px:0,py:0};
const K=a=>a.join(','),ad=(a,b)=>a.map((x,i)=>x+b[i]),su=(a,b)=>a.map((x,i)=>x-b[i]),dt=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),ln=a=>Math.sqrt(dt(a,a)),cl=e=>C[e]||'#ccc',ra=e=>R[e]||.65;
function tok(x){return x.match(/'(?:[^']*)'|"[^"]*"|\S+/g)||[]}function num(x){return +String(x).replace(/\(.*/, '')}
function parse(t){let l=t.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(x=>x&&!x.startsWith('#')),f=n=>{let x=l.find(x=>x.startsWith(n));return x?num(tok(x)[1]):NaN},a=f('_cell_length_a'),b=f('_cell_length_b'),c=f('_cell_length_c'),A=f('_cell_angle_alpha')||90,B=f('_cell_angle_beta')||90,G=f('_cell_angle_gamma')||90;if(![a,b,c].every(Number.isFinite))throw Error('Нет _cell_length_a/b/c');let r=x=>x*Math.PI/180,al=r(A),be=r(B),ga=r(G),v1=[a,0,0],v2=[b*Math.cos(ga),b*Math.sin(ga),0],x=c*Math.cos(be),y=c*(Math.cos(al)-Math.cos(be)*Math.cos(ga))/Math.sin(ga),v3=[x,y,Math.sqrt(Math.max(0,c*c-x*x-y*y))],sites=[];for(let i=0;i<l.length;i++)if(l[i].toLowerCase()==='loop_'){let j=i+1,h=[];while(l[j]?.startsWith('_'))h.push(tok(l[j++])[0]);let ix=h.indexOf('_atom_site_fract_x'),iy=h.indexOf('_atom_site_fract_y'),iz=h.indexOf('_atom_site_fract_z'),ie=h.findIndex(x=>x==='_atom_site_type_symbol'||x==='_atom_site_label');if(ix<0||iy<0||iz<0||ie<0)continue;while(j<l.length&&!/^(_|loop_|data_)/.test(l[j])){let z=tok(l[j++]);if(z.length>=h.length)sites.push({e:z[ie].replace(/[0-9+\-].*$/,''),f:[num(z[ix]),num(z[iy]),num(z[iz])]})}break}if(!sites.length)throw Error('Нет _atom_site_fract_x/y/z');return{v:[v1,v2,v3],sites,cells:new Map([[K([0,0,0]),[0,0,0]]]),atoms:[],bonds:[],mul:{}}}
function cart(f){return[dt(f,[S.v[0][0],S.v[1][0],S.v[2][0]]),dt(f,[S.v[0][1],S.v[1][1],S.v[2][1]]),dt(f,[S.v[0][2],S.v[1][2],S.v[2][2]])]}
function rebuild(){let m=new Map,e=1e-4;for(let c of S.cells.values())for(let s of S.sites){let o=s.f.map(x=>Math.abs(x)<e||Math.abs(x-1)<e?[0,1]:[0]);for(let x of o[0])for(let y of o[1])for(let z of o[2]){let p=cart(ad(s.f,ad(c,[x,y,z]))),id=s.e+p.map(x=>x.toFixed(4));m.set(id,{e:s.e,p})}}S.atoms=[...m.values()];S.bonds=[];let cut=+ui.cut.value;for(let i=0;i<S.atoms.length;i++)for(let j=i+1;j<S.atoms.length;j++){let a=S.atoms[i],b=S.atoms[j],d=ln(su(a.p,b.p));if(a.e!==b.e&&d>.001&&d<=cut)S.bonds.push([a.p,b.p])}panels();draw()}
const F=[[[ -1,0,0],['000','010','011','001']],[[1,0,0],['100','101','111','110']],[[0,-1,0],['000','001','101','100']],[[0,1,0],['010','110','111','011']],[[0,0,-1],['000','100','110','010']],[[0,0,1],['001','011','111','101']]],E=[['000','100'],['000','010'],['000','001'],['110','010'],['110','100'],['111','011'],['111','101'],['111','110'],['001','101'],['001','011'],['100','101'],['010','011']];
function corners(c){let r={};for(let x of [0,1])for(let y of[0,1])for(let z of[0,1])r[`${x}${y}${z}`]=cart(ad(c,[x,y,z]));return r}function faces(){let r=[];for(let c of S.cells.values()){let p=corners(c);for(let [n,ids]of F)if(!S.cells.has(K(ad(c,n))))r.push({c,n,p:ids.map(x=>p[x])})}return r}function edges(){let m=new Map;for(let c of S.cells.values()){let p=corners(c);for(let [x,y]of E){let a=p[x],b=p[y],k=[a,b].map(z=>z.map(x=>x.toFixed(5)).join()).sort().join('|');m.set(k,[a,b])}}return[...m.values()]}
function center(){let c=[...S.cells.values()],lo=[0,1,2].map(i=>Math.min(...c.map(x=>x[i]))),hi=[0,1,2].map(i=>Math.max(...c.map(x=>x[i])));return cart(ad(lo,ad(hi,[1,1,1])).map(x=>x/2))}function pr(p){p=su(p,center());let y=cam.y*Math.PI/180,x=cam.x*Math.PI/180,X=p[0]*Math.cos(y)+p[2]*Math.sin(y),Z=-p[0]*Math.sin(y)+p[2]*Math.cos(y),Y=p[1]*Math.cos(x)-Z*Math.sin(x);return[can.clientWidth/2+cam.px+X*cam.z,can.clientHeight/2+cam.py-Y*cam.z,p[1]*Math.sin(x)+Z*Math.cos(x)]}
function inside(p,a){let h=false;for(let i=0,j=a.length-1;i<a.length;j=i++){let x=a[i],y=a[j];if((x[1]>p[1])!=(y[1]>p[1])&&p[0]<(y[0]-x[0])*(p[1]-x[1])/(y[1]-x[1])+x[0])h=!h}return h}function hit(x,y){return faces().map(f=>({f,p:f.p.map(pr)})).filter(o=>inside([x,y],o.p)).sort((a,b)=>a.p.reduce((s,x)=>s+x[2],0)-b.p.reduce((s,x)=>s+x[2],0))[0]?.f}
function draw(){if(!S)return;let d=devicePixelRatio,w=can.clientWidth,h=can.clientHeight;can.width=w*d;can.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#777';ctx.lineWidth=1;ctx.setLineDash([3,3]);for(let[a,b]of edges()){a=pr(a);b=pr(b);ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}ctx.setLineDash([]);if(hover){let p=hover.p.map(pr);ctx.globalAlpha=.45;ctx.fillStyle='#d22';ctx.beginPath();ctx.moveTo(...p[0]);p.slice(1).forEach(x=>ctx.lineTo(...x));ctx.fill();ctx.globalAlpha=1}ctx.strokeStyle='#aaa';ctx.lineWidth=2;for(let[a,b]of S.bonds){a=pr(a);b=pr(b);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}for(let a of S.atoms.map(a=>({...a,q:pr(a.p)})).sort((a,b)=>a.q[2]-b.q[2])){let r=Math.max(3.5,ra(a.e)*(S.mul[a.e]||1)*cam.z/35);ctx.fillStyle=cl(a.e);ctx.beginPath();ctx.arc(a.q[0],a.q[1],r,0,7);ctx.fill();ctx.strokeStyle='#000';ctx.stroke()}}
function panels(){let n={};S.atoms.forEach(a=>n[a.e]=(n[a.e]||0)+1);ui.total.textContent=`Всего атомов: ${S.atoms.length}`;ui.stats.innerHTML=Object.entries(n).map(([e,x])=>`<div class=row><i class=dot style="background:${cl(e)}"></i>${e}: ${x}</div>`).join('');ui.radii.innerHTML='';for(let e of Object.keys(n).sort()){S.mul[e]??=1;let d=document.createElement('div');d.className='r';d.innerHTML=`<i class=dot style="background:${cl(e)}"></i><label>${e}</label><input type=range min=.1 max=3 step=.1 value=${S.mul[e]}><output>${S.mul[e]}</output>`;let i=d.querySelector('input'),o=d.querySelector('output');i.oninput=()=>{S.mul[e]=+i.value;o.value=i.value;draw()};ui.radii.append(d)}}
function fit(){cam={x:25,y:-35,z:Math.min(can.clientWidth,can.clientHeight)/8,px:0,py:0};draw()}ui.file.onchange=async()=>{try{let form=new FormData;form.append('file',ui.file.files[0]);let r=await fetch('/api/structure',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.detail);S={v:d.lattice,sites:d.sites,cells:new Map([[K([0,0,0]),[0,0,0]]]),atoms:[],bonds:[],mul:{}};ui.name.textContent=d.filename;ui.empty.hidden=true;rebuild();fit();ui.status.textContent='CIF загружен локальным сервером'}catch(e){alert(e.message)}};async function save(format){if(!S)return;let r=await fetch('/api/export/'+format,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({atoms:S.atoms,lattice:S.v,filename:ui.name.textContent})});if(!r.ok)return alert((await r.json()).detail);let a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='scene.'+format;a.click();URL.revokeObjectURL(a.href)}q('#save-cif').onclick=()=>save('cif');q('#save-xyz').onclick=()=>save('xyz');ui.cut.onchange=rebuild;q('#reset').onclick=fit;can.onpointerdown=e=>{can.setPointerCapture(e.pointerId);hover=hit(e.offsetX,e.offsetY);drag={x:e.offsetX,y:e.offsetY,s:e.shiftKey,m:false};draw()};can.onpointermove=e=>{if(!drag){let h=hit(e.offsetX,e.offsetY);if(h!==hover){hover=h;draw()}return}let x=e.offsetX-drag.x,y=e.offsetY-drag.y;drag.m||=Math.abs(x)+Math.abs(y)>3;if(drag.s){cam.px+=x;cam.py+=y}else{cam.y+=x/2;cam.x+=y/2}drag.x=e.offsetX;drag.y=e.offsetY;hover=null;draw()};can.onpointerup=()=>{if(drag&&!drag.m&&hover){let n=ad(hover.c,hover.n);S.cells.set(K(n),n);rebuild();ui.status.textContent='Добавлена одна ячейка'}drag=null;hover=null;draw()};can.onwheel=e=>{e.preventDefault();cam.z*=e.deltaY<0?1.15:1/1.15;draw()};new ResizeObserver(draw).observe(can);
